language: node_js
node_js:
- node
notifications:
  slack:
    secure: lF2TlTcWfzqM/H84mPNyJhhqwxwd7RjHlCp8irZ2DqSua9DLVzWJv+i5utQbT9y5sVQj2ZIN2K0CrpuxXtHJvOuM4u+tZXm0fFvjA+D7Txy2aKnh527WS2+4pzlTXyzMPTIHI3Qw8UVf1Rbr5jGiXkTP3Z9s94pneHuMooFhLLeGJD1hTxZwY5a6kDx1Iw0VpJxEhReVDQz9Zdsa+Sam07nAecHzJaIN7sfLrRmLDthDUSkLpq44ZD0g3bKxNPnU2lDFfbQ5dEc6u7XkAWpJPhvEfQBHKT8cZmhhczXbzI0mWAa+mSH1fISuXnK26/ogqDqf8wTYO2zRjLSL1uMIJG+05n7KtQc6tMQCbXUn/SFFz6u6Bxe6gkLJ+0oz6fbYWUxNXVUFqErA+IdU0NA5c03ZOomyEyZSWXpa30Tap2ZhYXzmdL65BYWQs3/iytmMk2W1XYfLds1nVslzMZnZYrZYiXxyUdZESCjvEj9wOF2KQz0wlWKscTrsbW3NdyJm6iCbVFtTfMobyk5ZZCAR6Et0Wg2SqEvsvG7ErfSN6SI0f1/QNTgz+VwVMg7akyYcvtvIQ5UeXAq1jayNiaXYCrZTH5ySUnbPKlMnrAPqij0+8C9rjkC2vVCGAUcW2R9RGQeunFGO+H7HTSUT2kQa3unQZFaKUxCZiCUQvlHXq2M=
