os:
  - linux
  - osx
language: node_js
node_js:
- node
notifications:
  slack:
    secure: tFLJ86JHzgC/9SlbYnQD0pROonRCgsfSB8XjddFAeroRLmcMxQ4DYQlKRAy87S90nDVbRXwKDD0BGdDvJagTUpFBfzNVXIrMlKBzpsCQ9Z6obWIFkld75EfJEKX559ley5sEliLRiicNjTbz9GdOlJnBWX+i8pdRXMzTqrbSudKi++Pl5zvq04A/TAiiNZn3gAT6uv6r7+b/3WHlnZekWXM14+NlifNdMzCOT6va4wWtO27qitfXqvtCBEBr6CNmaQC1JTTJ98BU9AxnEKAmAn3/JjGaIPEhdmQW2QQtUHchvGX9vmtz+187bu2MVC+YsenRbDsyw07pZfsi7fX4U2txOSB4513nQIKQAO9r6fPdtqux+HHx/i9fi+WFDIPKp6Hp1m7vgRSQedgXPDVgquQypxp32U4GlBy2M/TYknx89O8CPgSl2q1GcMk5pkoI/xzppz23elv05u/GmVih8KQrrz5S4MiAcgSOzQDca0WK6z3xaKr98RD1bmVM55xGr41hcVpyJEawcUBPC0Zlzg+yEh3zXYZOXkjHrwF4SoyXhXWDSKSf9osWbcWViMr8Trxsh3/TcEAQUviopQVNN67zpGpL7Lu75G5YHBwmCS3xnfeXHjG5BPiYGb0FXQZXxnY8mqM3jfmjYQUnHix3t/R3p1ugNHx8pumiZqb/T00=
script:
  flow check && yarn test
